### ISSUE TITLE
HRY-Core + Overwolf + OBS Studio causes game crash

### ISSUE THREAD

**Issue by shardick** [Hary309/hry-core#4] opened 2022-07-10 19:33 UTC
Hi,

i'm the creator of Trucky, an in-game overlay app based on Overwolf. 

We received many reports of HRY-Core causing game crash when used with Overwolf and OBS Studio capturing the game. If OBS capture the screen, the game works normally.

We have reproduced the issue directly with Overwolf support, it happens also without Trucky, it's necessary to have OBS Studio running. Without OBS Studio HRY-Core and Overwolf can be executed together.

I'm openining this issue, not only for Trucky itself, but also because Overwolf is used by milions of user all around the world.

Here attached the crash log:
[game.crash.txt](https://github.com/Hary309/hry-core/files/9079737/game.crash.txt)

Hope this helps and you can look into this issue

**Comment by Hary309** [comment] 2022-07-10 19:35
Thank you, I will take a look, sorry for the trouble.

**Comment by shardick** [comment] 2022-07-10 19:49
Thanks for your quick response. Please keep me updated in case you need something else

**Comment by Hary309** [comment] 2022-07-10 20:33
I tried to reproduce the bug, but it works fine for me. I have running hry-core, overwolf, trucky and obs studio (which captures the game) and it just works fine. 
Also, the game.crash.txt that you supplied doesn't have listed hry-core.dll in loaded modules, are you sure you send the right file?

**Comment by shardick** [comment] 2022-07-10 21:00
You're right about the last point: the game crash doesnt contains hry_core because in this scenario the game doesnt track anything, just crash and exit to the desktop.
Sorry for not have checked before.

Try to set OBS tracking the game and then restart the game a couple of time: if you set OBS with the game open and OBS hook into the game, wont crash.

![image](https://user-images.githubusercontent.com/518905/178161948-f6a79965-0a45-460a-b027-4a9a95e4813e.png)

**Comment by Hary309** [comment] 2022-07-10 21:23
I managed to crash the game, but it looks like the Trucky (or Overwolf) is catching the crash. Is there a way to look at the crash log?

**Comment by shardick** [comment] 2022-07-10 21:26
I dont think is Overwolf catching the crash, i dont think is possible. is a normal behaviour when the crash is at a lower level rather than created from the game itself.

**Comment by Hary309** [comment] 2022-07-11 20:49
Hi, I just released 1.0.6, with a hopefully fix. Would you be able to check if the crash still occurs? 
[https://github.com/Hary309/hry-core/releases/tag/1.0.6](https://github.com/Hary309/hry-core/releases/tag/1.0.6)
Download the **hry-core-runtime-1.0.6.zip** and replace hry-core.dll in `Euro Truck Simulator 2\bin\win_x64\plugins`

**Comment by shardick** [comment] 2022-07-12 06:45
Thanks @Hary309 .

That's surely better, doesnt crash anymore when Overwolf and OBS hook into the game with Game Capture but, at least for me, crashes when ALT+TAB, the game freeze and then close.

Tested also with Capture Third Party Overlay in OBS.

**Comment by Hary309** [comment] 2022-07-12 06:51
Also, could you send **hry_core.log** (`Documents/hry-core`), **game.log.txt** and **game.crash.txt** if generated?

**Comment by shardick** [comment] 2022-07-12 06:54
Fullscreen
[hry_core.log](https://github.com/Hary309/hry-core/files/9090282/hry_core.log)
[game.crash.txt](https://github.com/Hary309/hry-core/files/9090283/game.crash.txt)

**Comment by Hary309** [comment] 2022-07-12 06:56
Please try in windowed mode, I will try to reproduce this bug later.

**Comment by shardick** [comment] 2022-07-12 07:52
Windowed mode is ok. The issue persist only on fullscreen

**Comment by Hary309** [comment] 2022-07-12 19:04
Hi, I just released 1.0.7. I tested it on fullscreen and it works fine.

[https://github.com/Hary309/hry-core/releases/tag/1.0.7](https://github.com/Hary309/hry-core/releases/tag/1.0.7)

**Comment by shardick** [comment] 2022-07-12 21:49
Tested, works fine.
Thank you for your effort, truly appreciate

**Comment by Hary309** [comment] 2022-07-12 22:30
Great, thanks for the report and testing, it was a lot of help.
Closing the issue.

**Closed by Hary309** 2022-07-12 22:30 UTC
